# Generated by Django 4.2.3 on 2023-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_remove_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='main_post',
            field=models.BooleanField(default=False),
        ),
    ]
